log:
  log_dir: 'log'
  chkpt_dir: 'chkpt'


arcface:
  chkpt_path: '/workspace/Arcface.pth'
  vector_size: 256

data:
  dataset_dir: '/DATA/processed-dataset/train'
  valset_dir: '/DATA/processed-dataset/val-10'
  num_train_samples: 1000000

model:
  learning_rate_E_G: 4e-4
  learning_rate_D: 4e-4

  beta1: 0
  beta2: 0.999

  batch_size: 12

  num_workers: 48
  grad_clip: 0.0

  limit_train_batches: 1.0